sudo: false

branches:
  only:
    - master

os:
  - linux

language: python

python:
  - "3.5"

services:
  - postgresql: "9.4"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

before_script:
  - psql -c 'create database wasty;' -U postgres
  - psql -U postgres -c "create extension postgis"

script:
  - coverage run manage.py test

after_success:
  - coverage report
  - coveralls
